### ISSUE TITLE
delete folder 返回-166

### ISSUE THREAD

**Issue by MarsYoung** [tencentyun/cos-java-sdk#10]
实际上这个目录是存在的，并且目录下没有任何文件。

**Comment by wucheng** [comment]
这个通常是目录不存在， 建议把目录贴一下, 另外cos统一走工单系统，github的响应速度不快，如果有疑惑的话，建议通过提工单反馈，谢谢

**Comment by MarsYoung** [comment]
已经解决。。记得这个问题是由于 目录没加活着加了 斜杠导致的。。如果有时间的话，可以把这个优化下。

**Comment by wucheng** [comment]
嗯 我们也注意到了这个 3.3的java sdk对目录输入做了校验，要求必须以斜杠结尾
